### PR TITLE
create and update item using API without container

### PR DESCRIPTION
**Pull request by grootmax**
Existing: Notes are created and updated with container parameter

New Updates: Now we can create and update notes without passing container parameter and with passing container parameter

Reg:testing with playwright, I have been developing in codespace, so could not able to run few tests , but 90% of test is successful with playwright.
I have tested all possible scenario's using postman and it works good.

### CODE REVIEW

**Comment by raimohanska** [comment]
Quick review fix checklist.

- [ ] The "Create and update board" test fails at step "Change item container". Could you enable Github actions on your repository to see what happens on Github actions if you have limitations on running tests locally? In any case, successful tests is of course a requirement for merge.

- [ ] I see two commits with the same commit message. That's a bit unexpected
- [ ] The fixed coordinates in github-webhook are not acceptable. The item needs to be placed within the container bounds as earlierly. If you need to change the webhook code I suggest you add a test for the webhook. But most importantly, don't break it :)
- [ ] The x,ywidth,height attributes in the APIs must be optional, in order to preserve earlier functionality
- [ ] Existing test case where container ids are used must not be changed. They must pass as-is
- [ ] New test cases for new API parameters needed

**Comment by grootmax** [comment]
I made this changes in github-webhook as x,y,height and weight as required now

regarding x, y, weight, height  and container being a partial, is it possible

**Comment by raimohanska** [comment]
Sure you can make the attributes optional in the API, using the `optional` wrapper for the io-ts fields. We do not want to make breaking changes (as in making any new parameters like x, y mandatory) unless absolutely necessary. That's a general best practice in API design - don't break your users' code.

**Comment by raimohanska** [comment]
I guess you mean height instead of weight :) Happy hacking mate!

**Comment by grootmax** [comment]
yup!!! how about having separate api for sticky-note creation without a container and updation of sticky-note without a container

**Comment by grootmax** [comment]
deleted head due to this "I see two commits with the same commit message. That's a bit unexpected", having issues in codespace

**Comment by raimohanska** [comment]
I think it should be feasible to combine the container/x+y versions in the same endpoints as you did. Just make parameters optional so that

- If container is given, x and y are ignored and things work as in current `master` (actually not accepting would be optional)
- If x/y are given, container is ignored (actually denying it would be better). The Pro version would determine the current container based on coordinates and size, as in `maybeChangeContainerForItem`

You could use the `union` function of io-ts to support one of two alternative parameters (either x+y+width+height or optional container).

**Comment by grootmax** [comment]
yup!!! currently testing the changes, made all the changes in PUT

**Pull request closed without merging**
